### ISSUE TITLE
 Add repository page does not use the Status field when generating YAML

### ISSUE THREAD

**Issue by VictorLamoine** [rosindex/rosindex#149]
https://index.ros.org/contribute/add_repo/

Whatever `Status` is chosen in `4. Generate the YAML markup describing your repository` the resulting YAML description misses the `status` field:

```yaml
  industrial_robot_angle_conversions:
    doc:
      type: git
      url: https://gitlab.com/InstitutMaupertuis/industrial_robot_angle_conversions.git
      version: melodic
```
![image](https://user-images.githubusercontent.com/5566160/60654473-5dce1200-9e4c-11e9-9565-50736d917395.png)
